// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateTask(arg1:models.TaskRequest):Promise<models.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetTasks():Promise<Array<models.Task>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateTask(arg1:string):Promise<void>;
