// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['internal']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['internal']['App']['DeleteTask'](arg1);
}

export function GetTasks() {
  return window['go']['internal']['App']['GetTasks']();
}

export function Startup(arg1) {
  return window['go']['internal']['App']['Startup'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['internal']['App']['UpdateTask'](arg1);
}
